### ISSUE TITLE
Unable to start a backup

### ISSUE THREAD

**Issue by tackin** [KIMB-technologies/Radio-API#32]
Hi!
In the past I did my backups or relocation of the radio-API just by copying the ./data - folder to the new site. But now I wanted to try your new backup-function.
I tested the Nondockerversion with Apache. Works great with a tiny "less than 1MB-Storagefootprint" for the domain. ;-)
But ....
I found no direct-link to do a "Backup" in the GUI by clicking on it. So I just called:
http://wifiradiofrontier.com/gui/im-export.php
I added a token to env.json as suggested : "Nutzen Sie z.B. den Token TbscOdOBJjeVHrtB6CAw"
After that I called the page ../gui/im-export.php again and got the same message as before. "Der Import und Export ist für diese Installation deaktiviert! ...."

I might have got something wrong.
But a link to "click to make a backup" should be added to the gui anyway.

I also want to thank you for your current work investment to this project. 
It's already really working fine and every little extra you provide, is an other cherry on the cake. ;-)

**Comment by kimbtech** [comment]
Hi!

The default `env.json` might be a bit evil, because it contains a the token at the key `_CONF_IM_EXPORT_TOKEN`.
There the leading `_` needs to be removed, i.e., finally  `"CONF_IM_EXPORT_TOKEN" : "TbscOdOBJjeVHrtB6CAw"` should be in the file.

(My problem is, that JSON does not support comments and thus I used the leading `_`.)

**Comment by tackin** [comment]
... uuhhh!! You should mention it in the Setup.md

**Comment by tackin** [comment]
confirm! Works now.
