### ISSUE TITLE
Question ("How To" Videos)

### ISSUE THREAD

**Issue by Wurm200** [KIMB-technologies/Radio-API#37]
Hello 
I have a question.
Now that frontier nuvola wants to add fees, it would be nice if beginners could also use your Radip API. Would it be possible to provide a video of the complete installation to make it easier to understand? I have a server at AllInk, but I can't really get any further with the instructions.

**Comment by kimbtech** [comment]
Hi,  
the installation of Radio-API highly depends on the actual server, hosting, and setup.
Thus, I can not create a general video about the installation, e.g., a video about my setup would not help (most) other users.

However, I will answer questions about the installation here and try to help for each specific case and setup. 

In your case:
Do you have a dedicated server with an own IP (v4) address at All-Inkl?
In a shared hosting environment Radio-API presumably can not be installed/ will not work. 
The problem is that the requests of the radio need to be redirected to your installation of Radio-API and it needs to answer for request to the domain `.wifiradiofrontier.com`. 
Thus, in a shared hosting with a shared IP only one user can answer the requests to this domain name.
I assume All-Inkl will not (and also should not) allow to set `.wifiradiofrontier.com` as your domain name for you installation of Radio-API.

If you have a dedicated server or VPS with an own IP, Radio-API should be usable. 
In this case, please describe your issues.

**Comment by Wurm200** [comment]
No, I have a "normal" package with AllInkl (all-inclusive PrivatPlus).
Then I probably can't use this option =(

**Comment by kimbtech** [comment]
Sadly, with a web hosting you will not be able to run Radio-API.
You would need more control (e.g., root access) to the server.
At least I can not imagine how All-Inkl could make Radio-API possible in a shared hosting.

Generally, the main problem is, that the Radio requires exactly one kind of responses to its request.
And the targets etc. of the request can not be changed.
Thus, Radio-API requires a somewhat strict setup.

**Comment by Wurm200** [comment]
Sorry, that was my mistake, I'm not quite an expert and thought that would be enough.
Thanks for your help. =D

**Comment by kimbtech** [comment]
No worries, asking a question is never a mistake.
