### ISSUE TITLE
time.wifiradiofrontier.com

### ISSUE THREAD

**Issue by stoneubi** [KIMB-technologies/Radio-API#56]
Hi, 

I do have a question about the time handling. As decribed I managed my DNS resolver, pi-hole, do transfer all request for any *.wifiradiofrontier.com request to my / our great radio api. 

On my HAMA100IR radio I can configure that the radio should sync the time automatically. According to my log files this is done connecting to time.wifiradiofrontier.com. As I re-route all the request for *.wifiradiofrontier.com to the radio api I wonder if the radio api handels the time request. 

I think, this is not the case actually as my radio won't set up the right time automatically and I have to do this manually at the moment. This is not a big thing but as I recognize from my radio the time isn't always correct. Within a period of 4 week the radio is 2 to 3 minutes above correct time and therefore I don't think that the time is synced correctly for the moment. 

Many thanks
Stoneubi

**Comment by kimbtech** [comment]
Hi,

in fact there is an issue in the documentation/ installation guide. The radio expects an NTP server at the IP of `time.wifiradiofrontier.com`. My Radio-DNS image redirects all request except `time.wifiradiofrontier.com` to Radio-API, while `time.wifi...` gets redirected to an NTP-server (this may be `time.wifiradiofrontier.com` or any other, e.g., for Radio-DNS I use `ntp0.fau.de`).

Thus, your radio's time sync should work if you change the pi-hole to allow `time.wifiradiofrontier.com` and redirect all other requests of `*.wifiradiofrontier.com` to Radio-API. 

Thanks for the info regarding the setup guide, I will update it.

Some more info:
As you use a Hama-Radio, it should/ might be sufficient to only redirect `hama.wifiradiofrontier.com` to Radio-API. This is because for each radio vendor they have a different name as prefix for `.wifiradiofrontier.com` while the API stays mostly the same (small differences are handled by Radio-API). However these prefixes are somehow strange as `aldi` (like the German supermarket) is used for radios from Medion. Thus I recommend to redirect all of `*.wifiradiofrontier.com`.

There is also a server `update.wifiradiofrontier.com` from which the radio fetches new updates and checks if there is a new software version available. This server is blocked in Radio-DNS and I think it might be good idea to block it: (i) From my experience there are nearly never updates available for the radio.  (ii) Silicon Frontier could push an update to all radios which changes the API, blocks third party APIs, or removes features from the radio. Which would then lock us out from our radios or Radio-API.

**Comment by stoneubi** [comment]
Thank you for the quick reply. 

Maybe this is interessting for other people with pihole. 

This redirect has to be done in: /etc/dnsmasq.d/05-custom.conf 
After the change is done the dns has to be restarted with the command: pihole restartdns

I deleted the redirect for time.wifiradiofrontier.com

As a result the command: nslookup time.wifiradiofrontier.com now shows 
Name:   eps-loadmaster-hap.nuvolaservices.io
Address: 185.128.204.56

I think this has solved the time sync issue.

Thanks,
Stoneubi
