### ISSUE TITLE
KIMB-technologies/Radio-API

### ISSUE THREAD

**Issue by Sepphuber007** [KIMB-technologies/Radio-API#57]
Hello
 I have 4 wifi radios: all 4 were previously connected to wifi.

Now I have connected 2 to Lan and the broadcast list has disappeared on both (back to the original Frontier broadcast list). Switched the 2 back to wifi and still I can't get their list - what am I doing wrong?

Is it not possible to connect the radio to the Lan to get the broadcast list from them? KIMB-technologies/Radio-API

thx 
Sepp

**Comment by kimbtech** [comment]
Hi Sepp,

I do not use my Radio via ethernet, however, I can not imagine that using a wired connection instead of a wireless is a problem for Radio-API itself.

But I assume that the connection settings to redirect the requests to Radio-API instead of Silicone Frontier's API may need to be changed or redone.
E.g. the DNS server setting might be reset when connecting to an ethernet cable or DHCP gets enabled to fetch the default DNS server.

**Comment by Sepphuber007** [comment]
I have now switched it to wifi but unfortunately it is not working yet.
I have reset the radio dns runs via pihole as with the others.
2 radios are working and 2 are not can it be that when you switch it to wifi it takes a while until it is recognized?

thanks

**Comment by kimbtech** [comment]
Yes, this is possible. Typically DNS results/ answers have a TTL (time to live). Thus, the radio may only query the DNS server every x time units (for me it is 12 hours for `*.wifiradiofrontier.com`).
However, a good DNS implementation should clear this cache of results, when settings are changed, but I am not sure, if Radio clears it.

**Comment by Sepphuber007** [comment]
Thank you then I'll wait

**Comment by Sepphuber007** [comment]
Hello

The two radios use the same DNS and I only ever get:
Register http://nuvola.link/sr
Code:xxxxxx
Valid for 10 minutes
Do you happen to know another solution
I use Pihole but have not changed anything except that I have connected them directly to the LAN. Now they have been connected to the wifi again for 1 day and I still can't get your reg. favs that are stored on my Rapi,

At the moment I don't know what to do......

Thanks in advance Sepp

Translated with DeepL.com (free version)

**Comment by fletchg** [comment]
It looks like you need to fix your DNS on your radio side. You are trying
to connect to frontier-nuvola not KIMB's software. It looks like
frontier-nuvola disabled access until you reset your password and agree to
their new policies - which is a very good reason to switch to KIMB's
software.

**Comment by kimbtech** [comment]
Hi,
I assume the same issue fletchg points out.
Two radios still work well with your Radio-API installation, thus, the installation will not be the problem.
All four radios used to work with Radio-API, so the radios theselfes are be compatible, too.

Then, the only possible thing causing the problems are the DNS requests and thus, the redirect of the radios' requests to Radio-API. Especially, because the problems started after changing radios from Wifi to Ethernet.
However, I still not understand, why the radios stopped working with Radio-API after (re-)connecting via Wifi.

- Are you able to see all DNS requests the radios do? (Possibly Frontier changed something with their domains and we need to update something in the DNS? I checked their service, but did not notice any relevant changes.)
- Did the radios try to do an update after connecting via Ethernet?
- Did you notice any differences of the radios interface after connecting via Ethernet (besides missing Radio-API)?
- You may try to "Factory Reset" the radios. This will reset all settings of the radios to the default ones and after changing the DNS server again, the radios will hopefully work with Radio-API again. 

PS: If it is easier for you, you may also answer in German.

**Comment by Sepphuber007** [comment]
Danke das ich Deutsch auch schreiben kann. Ich habe den Fehler gefunden hab mir im Pihole den DNS Record gelöscht hama.wifiradiofrontier.com jetzt funktioniert wieder alles danke nochmal für eure Unterstützung.
lg Sepp

**Comment by kimbtech** [comment]
Super, dass es jetzt wieder funktioniert!
Mich hatte es echt schon sehr gewundert, wie das sein kann und ob Frontier Silicon angefangen hat, irgendwelche Maßnahmen gegen alternative APIs umzusetzen— glücklicherweise aber nicht 😀

**Comment by Sepphuber007** [comment]
Hallo Kurze frage kann ich bei Radio Api Plugin auch statt Redis das APCu als Caching system 1nehmen ?

lg Sepp
