### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by RotorStator** [KIMB-technologies/Radio-API#59]
Hello Everyone,

I have since years this radio :  **radio CGV dr30i**.
I have read your very interesting work to save my prefered radios but i am not able to use your files, i dont understand nothing and english is not my language and i have not the capacity to do all request by your files. Google translator of course can help me but the use of your files is too technicial for me.

I have a computer with Windows 11 family connected by Ethernet on Internet with a router (called BOX in France).
I have the radio connected on internet by ethernet
Please consider i am an old person and  i need some simple things 😜

Is it possible for you do a software like an internet browser maybe with all requested by the radio to see the list of my prefered radios and maybe to add others web radio and delete the closed radio in the list ? A software i have just to double click on it and all is ready ? Of course I can add some IP adress in a field if necessary but no much more.🤣

Tell me please if my request is possible or not and if you can release it. Or tell me if a software like that can already exists. 

Thank you so very much in advance

**Comment by RotorStator** [comment]
Thank you for your answer. 

I am from France as I have say it near the sentence : **router (called box in France.)**

I need a software to add and delete the web radios from mys playslists. Sometimes web radios are no more avalaible, so i need to delete it from the list. And I like to add new radios from all over the world, with very different languages, cultures and musics. This is my choice and I like to discover every day. 🥰

With my android 9 phone I use the very good application called UNDOCK  making my phone as a remote through the walls. This application can read all the mutilple lists of my 2 radios and many more things. I " _just_ " need a little more : a search windows and an add windows to my lists.

This is why i am asking and this is what i am asking. I hope all is clear. Thank you

**Comment by RotorStator** [comment]
I continue my internet searches. I have found this :

 https://aerogus.net/posts/hacker-radio-cgv-dr30i/

Very interesting too but not for me.

**Comment by tackin** [comment]
Oh I see! Bonyour d'Allemagne!

Well, this software does not what you might expect. It has nothing to do with the functions of the UNDOK-app (if we talk about the app from Frontier Smart Technologies) on your androidphone.

**Comment by RotorStator** [comment]
You are telling me that the software **Radio-API**  cant add or delete radios to the list ?

**Comment by RotorStator** [comment]
I forget one important thing 😒 : i am also a podcasts listener. My radios and the web service can do that, but now i cant add new podcasts. 😓

**Comment by tackin** [comment]
> You are telling me that the software **Radio-API** cant add or delete radios to the list ?

Yes!
It replaces absolute all of Frontier-network-services in the internet and makes Frontier-services unavailable for your UNDOK and your radios in your homenet.
After radio-API is running in your homenet, you also cannot use UNDOK anymore, as it needs the frontier-network-services from the internet to work.

**Comment by RotorStator** [comment]
What is the purpose of this sofware if it cant add radios and podcats in my radio lists ?

I am not sur I understand what you are telling me

**Comment by kimbtech** [comment]
Hi,
unfortunately, my French is not good enough to write an answer in French. You may try https://www.deepl.com/translator, which often provides better translations than Google Translate (at least using German and English).

This project, Radio-API, is a full drop-in replacement for the service of Frontier-Silicon (https://smartradio.frontier-nuvola.net/). Radio-API includes a database of radio stations and the possibility to add custom radio stations and also podcasts.

However, Radio-API is a software to be run on your own server for your radio. Thus, you would need to install Radio-API locally on some hardware and configure your box  (router) and the radio accordingly. The installation of a service like Radio-API is quite different from installing an application like Firefox on Windows.

---

Let me give you a slightly more abstract, but less technical and somewhat imprecise, description:

The radio internally uses a special web page. This web page contains all the radio stations and podcasts shown to the user in the radio's display. Normally, the special web page is provided by Frontier-Silicon for all their radios. However, now Frontier-Silicon disables some part of their special web page and thus, some features are not available to in radio any more. (And there are also some extra features only available  from Radio-API.)

Thus, for creating Radio-API, I analyzed the special web page of Frontier-Silicon and how the radio accesses this special web page. I then created a copy of the special web page with all the information the radio needs to display and play radio stations and podcasts. To make the radio use Radio-API, we trick the radio, such that the radio accesses our special web page of Radio-API instead of the special web page of Frontier-Silicon.

Hence, in the end, Radio-API is a program which provides a web page for Frontier-Silicon radios and allows the users of Radio-API to add various kinds of custom radio stations and podcasts. The fact, that Radio-API provides a web page, indicates that installing Radio-API is similar to setting up a small web page in the internet (of course, with some differences, but overall similar technical requirements).

(The link, https://aerogus.net/posts/hacker-radio-cgv-dr30i/, mentioned above, shows some facts about this special web page used by the radio.)

---

Generally, it would be possible for someone to host a publicly available version of Radio-API. Then, only some configuration in a radio would need to be changed for a radio to use Radio-API. However, Radio-API a free and open source project and hosting a web pages costs some money and implies things like imprints and privacy policies. Thus, I only publish the code to be used by others on their own.

Finally, in your case, Radio-API seems not to be right the project for your needs. This is mostly due to Frontier-Silicon making in very difficulty to add custom stations and podcasts (like said above "to [...] use Radio-API, we trick the radio,").

**Comment by RotorStator** [comment]
Hello KIMBtech,

Thank you very very much for your long answer and explanations.👍

I have understood and released now that my computer become the server if I use your API **and of course must be ON to resolve all the adresses of radios and podcasts**. Is that correct ?   

The funny is when I used the radios my computer is OFF. 😂

So your project is not for me as you say. My need is only to add and remove some radios and podcasts from the lists in my 2 radios

I will continue to use my radios with Internet until the service will close definitively as it was the fact with the previous service I have on them until 2019 : https://srsupport.frontier-nuvola.net/portal/en/kb/articles/pourquoi-le-changement-du-service-le-7-mai-2019

Thank you very much KIMB. 👍👍👍You can close my request.
